### ISSUE TITLE
Add pairwise constraints manually

### ISSUE THREAD

**Issue by heriopaz** [piotrlasek/clustering#6]
Hello everyone, 

I'm currently working with your implementations of C-DBSCAN and C-NBC algorithms.  I've managed to do successful executions with both on Linux using random constraints, taking the file run-kmeans-tests.sh as en example. However, I'm having difficulties to manually provide pairwise constraints to the algorithm. Which is the formatting supported by the algorithms in order to identify the constraint set in an input file? Looking at the birch dataset files, I've tried to create files like the one below (using the Compound dataset as an example):

35.45,18.7      8.25,16.65      0
11.25,11.1      32.9,15.7       0
10.65,9.55      15.85,9.95      0
17.05,6.25      13.15,20.8      0
30.4,17.85      18.3,12.75      0
27.7,20.85      30.4,17.85      1
13.4,11.65      11.25,11.85     1
38.25,16.35     35.45,17        1
17.75,20.55     18.3,18.1       1
10.05,11.85     12.85,9.05      1

With pairs of instances represented by their attributes and a 0 or 1 flag for cant-link and must-link constraints respectively, with all three columns separated by a '\t' character. However, I get a warning of [main] WARN  ClusteringAlgorit  49 No constraints set. Am I doing it wrong in the file format or in the parameter declaration? Here's the contents my .sh file, I uncomment one of the r lines depending of the desired configuration, both lines with ic:random_10 (or any other number) works fine.

#!/bin/bash

echo -----------------------------------------------------------------------
echo Start.
echo -----------------------------------------------------------------------

m=Main
cp='.:../lib/*'

wp="workspacepath=./.."
dt="data=/data/new-data/Compound.txt"
al=algorithm
cdbs="$al=C-DBSCAN"
cnbc="$al=C-NBC"
pr="parameters=\"dump"

f='csts.txt'

#r="java -cp $cp $m $wp $dt $cdbs $pr;Eps:5;MinPts:5;d:3;ic:random_10\""
#r="java -cp $cp $m $wp $dt $cdbs $pr;Eps:5;MinPts:5;d:3;ic:$f\""
#r="java -cp $cp $m $wp $dt $cnbc $pr;k:5;ic:random_10\""
#r="java -cp $cp $m $wp $dt $cnbc $pr;k:5;ic:$f\""

echo $r
$r 

Thanks in advance,
Hério Sousa

**Comment by piotrlasek** [comment]
Dear Herio Sousa,

Regarding setting constraint please have a look at the following class:
[image: image.png]
I guess you will have to add an else-if section for your dataset.

Best
- Piotr

**Comment by heriopaz** [comment]
Hi Piotr,

Thanks for answering! However it seems that the image wasn't attached to the message, I can't visualize it.

**Comment by piotrlasek** [comment]
Hi,

Class name is: InstanceConstraintsAlgorithm
Method name: setConstraints(String)

You can use my e-mail instead of using github e-mailing system.
My address is piotr.lasek@gmail.com

Best,
Piotr

**Comment by heriopaz** [comment]
Thanks for the help, 

That's exactly what I needed! I'll email you directly in case of further questions.
